id: P5DCAD99A
initial_creation_type: input
source_metadata:
  title: Yeshe Tsogyal Series
  language: de
  description: 'Texts related to Yeshe Tsogyal (ye shes mtsho rgyal), the consort
    of Guru Padmasambhava:'
  volume:
    8440d8caf56247a09111ff492f1943d6:
      title: A Prayer to Khandro Yeshé Tsogyal
      parent: Prayers
    e6b02b3735da4aacb9acfb92c3697af4:
      title: A Prayer to Lady Yeshe Tsogyal, the Mother
      parent: Prayers
    66e5a348d0bd41adac3dc51a40b2fbde:
      title: A Prayer to Yumka Tsogyal
      parent: Prayers
    22a494e69190462e83b2185b9216f8a0:
      title: Prayer to Yeshe Tsogyal
      parent: Prayers
    85a73d6b5b694cca8189698ce1499b45:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    ca41a5f6de334c1585be343b7b731d32:
      title: Yeshe Tsogyal's Prayer
      parent: Prayers
    8aad965a68cb48f58c131c16eab5b0e0:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
created_at: '2022-03-01T02:03:05.118293'
last_modified_at: '2022-03-01T02:03:05.118295'
